default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: morning_pages_api_development

test:
  <<: *default
  database: morning_pages_api_test

production:
  <<: *default
  database: morning_pages_api_production
  username: morning_pages_api
  password: <%= ENV["MORNING_PAGES_API_DATABASE_PASSWORD"] %>
