name: build

on:
  push:
    branches: [develpoment]
  pull_request:
    branches: [development]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: morning_pages_api
          POSTGRES_DB: morning_pages_api_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Install PostgreSQL 12 client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Setup test database and Build
        env:
          RAILS_ENV: test
          PGHOST: localhost
          POSTGRES_DB: morning_pages_api_test
          POSTGRES_USER: morning_pages_api
          POSTGRES_PASSWORD: postgres
        run: |
          bundle install
          bundle exec rails db:create db:migrate
      - name: Test with RSpec
        env:
          PGHOST: localhost
          POSTGRES_DB: morning_pages_api_test
          POSTGRES_USER: morning_pages_api
          POSTGRES_PASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: bundle exec rspec
      - name: Publish code coverage
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
