name: build

on:
  push:
    branches: [develpoment]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Setup test database and Build
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: myapp
        run:
          bundle install
          bundle exec rails db:create db:migrate
      - name: Test with RSpec
        run: |
          bundle exec rspec
      - name: Publish code coverage
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
